server:
  port: 15005

spring:
  application:
    name: bilibili-main
  datasource:
    url: jdbc:mysql://124.223.99.166:3306/imitation-bilibili?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: L200107208017./@
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      enable: on
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1GB
  elasticsearch:
    uris:
      - http://120.48.67.55:9200
    username: elastic
    password: 111111
  data:
    redis:
      cluster:
        nodes:
          - 124.222.22.217:6379
          - 124.223.99.166:6379
          - 124.221.154.235:6379
        max-redirects: 3
      password: L200107208017@./
baidu:
  develop:
    auth:
      url: https://aip.baidubce.com/oauth/2.0/token
    clientId: sbjRmx1aqUBE1FRicpKfh4M1
    clientSecret: 7T6E3sajEAqkA38klRVGaXusNYB0QbZC
    splitBody:
      url: https://aip.baidubce.com/rest/2.0/image-classify/v1/body_seg

minio:
  endpoint: http://124.222.22.217:9000 # Minio服务所在地址
  accessKey: jey5fGaOYDCg6iPB # 访问的key
  secretKey: snJFuPAlLuJ8Mu9n9gRaytYV3V87WucK # 访问的秘钥
  #  defaultBucket: default
  downloadUri: http://124.222.22.217:9000
  path: http://124.222.22.217:9000

logging:
  level:
    io.juneqqq: DEBUG

rocketmq:
  name:
    server:
      address: 124.222.22.217:9876

# XXL-JOB 配置
xxl:
  job:
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8989/xxl-job-admin
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: xxl-job-executor-bilibili
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: logs/xxl-job/jobhandler
    accessToken: juneqqq

service-thread-pool:
  core-size: 100
  max-size: 100
  keep-alive-time: 60